ARG BASE_IMAGE=seleniarm/standalone-chromium:latest
FROM ${BASE_IMAGE}
USER root
RUN apt-get update -qq && apt-get install -y -qq --no-install-recommends xdotool xclip && rm -rf /var/lib/apt/lists/*
USER seluser
